import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base='examples/welcome',assets={};
for(const name of (await fs.readdir(base+'/assets')).sort())assets[name]=await fs.readFile(base+'/assets/'+name,'utf8');
const samples={en:await fs.readFile(base+'/en.md','utf8'),ko:await fs.readFile(base+'/ko.md','utf8'),assets};
const size=Buffer.byteLength(JSON.stringify(samples));
if(size>500000)throw Error('Bundled welcome sample exceeds 500 KB');
const logo=assets['aaeu-logo.svg'],hash=createHash('sha256').update(logo).digest('hex');
const brands=[];
for(const [id,name]of [['achmage','journal-of-achmage'],['command-space','journal-of-command-space']]){
  const bytes=await fs.readFile('assets/brands/'+name+'.pdf'),sha256=createHash('sha256').update(bytes).digest('hex');
  brands.push({id,data:Array.from(bytes),asset:{id:'brand-'+id,name:name+'.pdf',mime:'application/pdf',bytes:bytes.length,sha256,path:'assets/'+sha256+'.pdf'}});
}
await fs.writeFile('src/journal/sample.generated.ts','// Generated by scripts/generate-sample.mjs. Edit examples/welcome instead.\nexport const SAMPLE_FILES = '+JSON.stringify(samples)+';\nexport const SAMPLE_LOGO = '+JSON.stringify({id:'aaeu-demo-logo',name:'Academic Editor Ultra.svg',mime:'image/svg+xml',bytes:Buffer.byteLength(logo),sha256:hash,path:'assets/'+hash+'.svg'})+';\n');
console.log('Welcome sample: '+size+' bytes');
await fs.writeFile('src/journal/brands.generated.ts','// Generated from assets/brands. Original vector PDFs.\nexport const JOURNAL_BRANDS = '+JSON.stringify(brands)+';\n');
