import type {PropertySpec} from './markdownProperties';

const labels:Record<string,string>={schema:'Property schema version',template:'Journal template',title:'Article title','running-title':'Short running title','running-authors':'Running authors',doi:'DOI',year:'Publication year',volume:'Volume',issue:'Issue',received:'Received',revised:'Revised',accepted:'Accepted','copyright-year':'Copyright year','first-page':'First page','publication-mode':'Publication status',abstract:'Abstract',keywords:'Keywords','reference-checks':'Reference checks','sidebar-order':'Sidebar order','corresponding-name':'Corresponding author name','corresponding-email':'Corresponding author email','corresponding-address':'Corresponding author affiliation and address'};
const furniture:Record<string,string>={publication:'Publication information',copyright:'Copyright','header-even':'Even-page running head','header-odd':'Odd-page running head',folio:'Page number'};
const statements:Record<string,string>={data:'Data availability statement',funding:'Funding information',conflict:'Conflict of interest',acknowledgments:'Acknowledgments',ethics:'Ethics statement',contributions:'Author contributions'};
export function localizedProperty(s:PropertySpec,language:string):PropertySpec{
  if(language.toLowerCase().startsWith('ko'))return s;
  const key=s.key.replace(/^aaeu-/,''),indexed=key.match(/^(author|affiliation|sidebar|statement)-(\{n\}|\d+)-(.+)$/);
  let label=labels[key];
  if(indexed){const [,group,n,field]=indexed;label=({author:'Author',affiliation:'Affiliation',sidebar:'Custom information',statement:'Additional statement'})[group]+' '+n+' — '+({name:'name',text:'text',title:'title',label:'label',email:'email',address:'address',affiliations:'affiliation numbers',corresponding:'corresponding author',hide:'hide'} as Record<string,string>)[field];}
  for(const [prefix,title]of Object.entries({...furniture,...statements}))if(!label&&key.startsWith(prefix+'-'))label=title+' — '+(key.endsWith('-hide')?'hide':key.endsWith('-omission-reason')?'reason for omission':'text');
  if(/^sidebar-(received|revised|accepted|correspondence)-hide$/.test(key))label='Hide '+key.split('-')[1];
  const location=s.group==='statements'?'Immediately before References':s.group==='furniture'?(key.startsWith('copyright')?'First-page footer':key.startsWith('publication')?'First-page upper left':'Running head and page number from page two'):s.group==='publication'?(/^(corresponding|sidebar|received|revised|accepted)/.test(key)?'Beside the abstract on page one':'First-page publication information'):s.group==='abstract'?'First-page abstract panel':'First-page title and author area';
  const description=key.endsWith('-hide')?'Hide both the information and its label in the output. Entered values are retained.':key.endsWith('-omission-reason')?'Record why required journal information was omitted. This reason is not printed.':Object.keys(furniture).some(k=>key===k+'-text')?'Leave blank to use the template default. Custom text survives template changes. Variables such as {year} and {page} are supported.':key==='abstract'?'The abstract panel grows with its content. Use blank lines to separate paragraphs.':s.group==='statements'?'Enter the statement appropriate to your manuscript. The editor does not invent declarations.':key.includes('affiliations')?'Enter the numbers of this author’s affiliations. Add the affiliations first.':'Enter the information to print. The selected journal template supplies fonts, colors and placement.';
  const example=key==='title'?'Thinking with AI':key==='abstract'?'Enter the purpose, methods and findings in one or more paragraphs.':key==='keywords'?'AI, learning, writing':s.example;
  return {...s,label:label??s.label,description,location,example};
}
